version: "3.8"

services:
  web:
    image: michael73100/newtest:latest
    container_name: newtest_web
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    labels:
      - "runtipi.app.name=Page Web Anim√©e"
      - "runtipi.app.description=Page web moderne avec des animations JavaScript interactives"
